### ISSUE TITLE
PNPM version conflict with PNPM Lock File

### ISSUE THREAD

**Issue by othsueh** [JacobLinCool/homework-space#2]
error in pack.yml, PNPM version is not compatible with version in pnpm-lock.yml
``` yml
 - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7.17.1
                  run_install: true
```
